theme: jekyll-theme-minimal
title: Jean-Baptiste Lamare
description: Personal Website
logo: assets/img/enlitic.jpg
show_downloads: false
google_analytics: UA-180164542-1
plugins:
  - jekyll-seo-tag
github: [metadata]
